version: "3.9"

services:
  sonarqube:
    image: sonarqube:9.1.0-community
    restart: always
    cpu_shares: 500
    mem_limit: '2g'
    depends_on:
      - sonarbdd
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarbdd:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - devops-net


  sonarbdd:
    image: postgres:12
    restart: always
    cpu_shares: 500
    mem_limit: '1g'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - devops-net


  gitlab:
    image: 'gitlab/gitlab-ce:15.11.11-ce.0'
    restart: always
    cpu_shares: 1024
    mem_limit: '4g'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_EXTERNAL_URL:-https://gitlab.local.lan}'
        puma['worker_processes'] = 0
        sidekiq['max_concurrency'] = 10
        prometheus_monitoring['enable'] = false
    ports:
      - '80:80'
#      - '443:443'
#      - '22:22'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - devops-net


  jenkins:
    image: rg.fr-par.scw.cloud/ilkilabs/jenkins:latest
    restart: always
    cpu_shares: 500
    mem_limit: '1g'
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "5000:5000"
    group_add:
      - "998"
    networks:
      - devops-net

volumes:
  jenkins_data: {}
  gitlab_config: {}
  gitlab_logs: {}
  gitlab_data: {}
  sonarqube_data: {}
  sonarqube_extensions: {}
  sonarqube_logs: {}
  postgresql: {}
  postgresql_data: {}

networks:
  devops-net:
    driver: bridge
